services:
  db:
    image: timescale/timescaledb-ha:pg18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - 5432:5432
    volumes:
      - db_data:/home/postgres/pgdata/data
      - ./docker/tsdb/100_setup_db.sql:/docker-entrypoint-initdb.d/100_setup_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 50

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - 3020:3001
    volumes:
      - ./migrations:/app/migrations
      - ./src:/app/src
      - ./skills:/app/skills
      - ./skills.yaml:/app/skills.yaml
      - ./package.json:/app/package.json
      - ./bun.lock:/app/bun.lock
      - ./tsconfig.json:/app/tsconfig.json
    command: bun run --watch src/index.ts http

volumes:
  db_data:
